image: golang:1.14-buster

variables:
  REPO_NAME: github.com/freddieptf/manga-scraper

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go get -v ./...

stages:
    - test
    - build

format:
    stage: test
    script:
      - go fmt $(go list ./...)
      - go vet $(go list ./...)
      - go test -v -timeout 150s -race $(go list ./...)
  
compile:
    stage: build
    script:
      - os=linux arch=amd64; env GOOS=$os GOARCH=$arch go build -o $CI_PROJECT_DIR/build/mangadex-$os-$arch ./cmd/mangadex
      - os=darwin arch=amd64; env GOOS=$os GOARCH=$arch go build -o $CI_PROJECT_DIR/build/mangadex-$os-$arch ./cmd/mangadex
      - os=linux arch=amd64; env GOOS=$os GOARCH=$arch go build -o $CI_PROJECT_DIR/build/mangareader-$os-$arch ./cmd/mangareader
      - os=darwin arch=amd64; env GOOS=$os GOARCH=$arch go build -o $CI_PROJECT_DIR/build/mangareader-$os-$arch ./cmd/mangareader
    artifacts:
      paths:
        - $CI_PROJECT_DIR/build/*
